wrapper:
  identifier: mathis
  name:  Mathis Coater
  description: Semantic wrapper for the Mathis coating and drying equipment

ontology:
  channel_prefix: mathis-table
  channel_namespace: https://w3id.org/mathis-table/public/ontology#
  channel_ontology_iri: https://w3id.org/mathis-table/public/ontology

  individuals_prefix: mathis-ind
  individuals_namespace: https://w3id.org/mathis-ind/public/ontology#
  individuals_ontology_iri: https://w3id.org/mathis-ind/public/ontology

  domain_prefix: mathis
  domain_namespace: https://w3id.org/mathis/public/ontology#
  domain_ontology_iri: https://w3id.org/mathis/public/ontology

semantic_model:
  measurement_channel_class: emmo:EMMO_0f6f0120_c079_4d95_bb11_4ddee05e530e
  control_channel_class: coater:CommandInput

  measurement_process_class: chameo:CharacterisationMeasurementProcess
  control_process_class: mathis-table:DeviceControlProcess

  measurement_device_property: chameo:hasMeasurementSample
  control_device_property: chameo:hasInteractionWithSample

  measurement_output_property: emmo:EMMO_c4bace1d_4db0_4cd3_87e9_18122bae2840
  control_input_property: emmo:EMMO_36e69413_8c59_4799_946c_10b05d266e22

  timestamp_property: equipment:hasDateTimeStampData
  unit_property: emmo:EMMO_bed1d005_b04e_4a90_94cf_02bc678a8569

files:
  channels: config/channels.csv
  individuals: ontology/mathis_individuals.ttl
  generated_ontology: generated/table_channels_mathis.ttl
  nodelist: generated/nodelist.csv
  database_schema: generated/init.sql
  visualization: generated/visualization/graph.html
  dashboard_config: config/dashboard.yaml
  dashboards: generated/dashboards